### ISSUE TITLE
Typescript error "Excessive stack depth" for `hasAtLeast`

### ISSUE THREAD

**Issue by zavod008** [remeda/remeda#572] opened 2024-03-16 12:09 UTC
![image](https://github.com/remeda/remeda/assets/20419214/57d659cc-f19d-4ead-a594-9ba834d1067f)

 "remeda": "^1.50.1",
 "typescript": "~5.4.2"

**Comment by eranhirsch** [comment] 2024-03-16 14:36
Can you provide more context on what code is causing this, preferably with a typescript playground link or a code sandbox? I don't know of any specific issue right now with `hasAtLeast` and can't reproduce a trivial one myself:

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgCwIYGcCCMAyBTDeAXzgDMoIQ4AiKPEPAE1WoG4AodgYwgDt14zGKjgBeOAG0AunAxxeAVxAAjPFGkd2wUnAAUaLLgIDdQ1ABo4AZgCUNxOzhwe-CABs8AOjcQA5qdRhGw4nAHpQp0iouAA9AH52InYgA

There is currently an issue with Typescript 5.4 that was recently fixed; I would wait to update Typescript to 5.4 until version 5.4.3 comes out.

**Comment by eranhirsch** [comment] 2024-03-16 14:39
See #559 (although I can't say if they are related yet)

**Comment by zavod008** [comment] 2024-03-16 14:59
Sorry, I don't have time to pay much attention to this issue, for myself I just rolled back

**Comment by cjquines** [comment] 2024-03-20 02:30
i don't think it's related to #559 , since that's been fixed in the nightly and [the type is still broken](https://www.typescriptlang.org/play?ts=5.5.0-dev.20240319#code/C4TwDgpgBAShCGATA9gOwDYgCoFczogB4sAaKAOSggA9gJVEBnKVHAWwCMIAnMmK2vSZQsAbQC6UALxQJAPmkAoAJAxRAcgKoA5sAAW6yTToNm5RVEtQA-FG4IUGELIB0bmOItWAXLAdpMXHwiUgoyUVC3Fw85AG5FRVBIKABBbm54EABZAEtUcmIySmMhZlZOHgUZcq5uARNhc0tbNIyQYjkvX2LBUygABi9m1PTMjqGoX1EouCQA7DwCQoo5MijWsaw5cXjFRAgAY3R4eygAMxxUA+ActCg9eEYU4AAZBEZgZZ6GsvZauQAFF5EPBgPBfLNHJgNu0tiQvGw8jk2OxuvCAJS+EFgqA5Zgw3L5L5xIA)

i've bisected it to microsoft/typescript#56004

not sure if this is intended behavior, and the repro is rather large, so i haven't filed an issue yet

**Closed** 2024-03-31 19:10 UTC
Labels: bug, typing
