### ISSUE TITLE
Ramda - deepMerge

### ISSUE THREAD

**Issue by liel-almog** [remeda/remeda#406] opened 2023-11-04 19:12 UTC
There is no "good first issue" so I will write it plain,
I am using Ramda for a long time and one of my favorite utility functionalities is the "mergeDeep".
One of my biggest pain is that it is not type-safe and I would really like if it can be done.
I know there was an attempt of trying to get this into the code-base.
I'm bringing this up so other could support it.

Thank you!

**Comment by TkDodo** [comment] 2023-11-05 11:10
it's in the works, see:
- https://github.com/remeda/remeda/pull/317

**Comment by TkDodo** [comment] 2023-11-05 11:11
duplicate of
- #41

**Closed by TkDodo** 2023-11-05 11:11 UTC

**Comment by liel-almog** [comment] 2023-11-05 12:52
Thanks
